- name: 'registering system with subscription-manager'
  redhat_subscription:
    state: present
    username: "{{ username }}"
    password: "{{ password }}"
    pool_ids: "{{ pool_ids }}"
  tags: always

- name: 'disabling all repos'
  rhsm_repository:
    name: '*'
    state: disabled
  tags: always

- name: 'enabling the repos'
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items: "{{ repos }}"
  tags: always
