- name: 'set facts for ssh'
  set_fact:
    _key_gen: "{{ key_gen | default(True) }}"
  tags: always

- name: 'generate ssh key'
  command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
  args:
    creates: /root/.ssh/id_rsa
  register: out
  when: "_key_gen"
  tags: always

- debug: var=out.stdout_lines
  when: "_key_gen"
  tags: always

- name: 'make sure sshpass is installed on host machine'
  command: rpm -q sshpass
  register: cmd
  ignore_errors: True
  tags: always

- name: 'fail if sshpass is not installed'
  fail:
    msg: 'rpm sshpass in not installed on host, 
    It is a dependency for passwordless ssh authentication'
  when: cmd.rc != 0
  tags: always

- name: 'make password less ssh authentication'
  command: sshpass -p "{{ password }}" ssh-copy-id -o \
      "StrictHostKeyChecking=no" -f "root@{{ item }}"
  with_items: "{{ hosts }}"
  tags: always
